version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: your_password
    ports:
      - 5432:5432
    networks:
      - swarmnet

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - swarmnet

  beanstalk:
    image: schickling/beanstalkd:latest
    ports:
      - 11300:11300
    networks:
      - swarmnet

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - swarmnet

networks:
  swarmnet:
    external: true  
