version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: your_password
    ports:
      - 5432:5432
    networks:
      - swarmnet

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - swarmnet

networks:
  swarmnet:
    external: true  
