version: '3.1'

services:

  beanstalk:
    image: schickling/beanstalkd:latest
    ports:
      - 11300:11300
    networks:
      - swarmnet

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - swarmnet

  adminpanel:
    image: kikohernandez92/laravel:latest
    ports:
      - 8000:8000
    networks:
      - swarmnet
    entrypoint: ["execute"]

networks:
  swarmnet:
    external: true
